### ISSUE TITLE
Feature: SNOMED-CT Mapping for body-part examined

### ISSUE THREAD

**Issue by kapsner** [miracum/dicom-fhir-converter#2]
In function `gen_bodysite_cr` (https://github.com/miracum/dicom-fhir-converter/blob/master/dicom2fhir/dicom2fhirutils.py#L199) add mapping to map the provided value from the dicom-header (argument `bd`) to SNOMED-CT.

I'd suggest to do this in a stepwise manner:
1) first, copy the mapping table from [here](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_l.html) to mapping csv file and add this to the repo (should be sufficient to add 2 columns: "CodeValue" and "Body Part Examined")
2) if the first thing works, everything should be temporarily fine. to make it nice, in a second step the mapping via the csv-table could be replaced by a scraping of the webpage to always retrieve the latest version of the mapping table.

**Comment by alexa-ian** [comment]
Resolved with pull request: https://github.com/kapsner/dicom-fhir-converter/pull/2

**Comment by alexa-ian** [comment]
Ich habe beim weiteren Testen gemerkt, dass es bei den Test-Daten vorkommt, dass "Body Part Examined" zwar befüllt ist, aber mit einem nicht-DICOM-konformen Wert. 
Z.B. habe ich gefunden: "LEG" (gibt es gar nicht) oder "ABD PELVIS" (erwartet wäre "ABDOMENPELVIS"). Demnach gibt es für solche Fälle natürlich kein SNOMED-Mapping und der BodyPart in der FHIR-Ressource bleibt leer. 
Ich sehe dafür 3 Möglichkeiten: 
- Man lebt damit und hat im Zweifel dann halt keinen BodyPart in der Ressource
- Man mappt nur, wenn auch ein SNOMED-Wert verfügbar ist und lässt sonst den nicht-konformen Wert stehen (wäre dann aber eigentlich nicht konform mit der ImagingStudy)
- Man versucht, diese nicht-konformen Werte erstmal noch auf DICOM-Werte zu mappen. Wäre aber vermutlich keine ganz kleine Sache - kann ich gerade nicht abschätzen. 

Was sagst Du? @kapsner

**Comment by kapsner** [comment]
Ich würde vorschlagen, diese Fälle irgendwie zu kennzeichnen.

Z.B. https://github.com/alexa-ian/dicom-fhir-converter/blob/main/dicom2fhir/dicom2fhirutils.py#L61C1-L64C69

```pyhton
def _get_snomed(dicom_bodypart, sctmapping):
    # codes are strings
    sct_val = sctmapping.loc[sctmapping['Body Part Examined']
                          == dicom_bodypart]["Code Value"].values[0]
    if sct_val = "":
        sct_val = "ERROR: SCT for " + dicom_bodypart + " not found"
    return sct_val
```
